### ISSUE TITLE
Docker keeps appending "-1" to containers

### ISSUE THREAD

**Issue by ValenteXD** [Mathamen/trabalho-padroes-software#1]

**Comment by Mathamen** [comment]
check this https://github.com/testcontainers/testcontainers-java/issues/149

**Comment by ValenteXD** [comment]
Got it figured out
![image](https://github.com/user-attachments/assets/79678d23-99dc-4a52-8348-a6f8dbb8259c)

At the end of the day this was the solution to controling image and container naming:
https://forums.docker.com/t/custom-container-name-for-docker-compose/48089/6
